"""add agent_documents

Revision ID: 4683ba6f380c
Revises: d71db27e7d96
Create Date: 2026-06-21 11:14:53.737819

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "4683ba6f380c"
down_revision: Union[str, None] = "d71db27e7d96"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_documents",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("storage_key", sa.String(length=500), nullable=True),
        sa.Column("mime_type", sa.String(length=100), nullable=False),
        sa.Column("tags", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("source", sa.String(length=30), nullable=False),
        sa.Column("namespace", sa.String(length=50), nullable=False),
        sa.Column("slug", sa.String(length=200), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "namespace", "slug", name="uq_agent_docs_user_ns_slug"),
    )
    op.create_index(
        "ix_agent_documents_namespace", "agent_documents", ["user_id", "namespace"], unique=False
    )
    op.create_index("ix_agent_documents_user_id", "agent_documents", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_agent_documents_user_id", table_name="agent_documents")
    op.drop_index("ix_agent_documents_namespace", table_name="agent_documents")
    op.drop_table("agent_documents")
    # ### end Alembic commands ###
