"""add policies and insurance_targets tables

Revision ID: 5474ef0df2f2
Revises: e6cb7ee51794
Create Date: 2026-07-16 09:24:58.761878

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5474ef0df2f2"
down_revision: Union[str, None] = "e6cb7ee51794"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "insurance_targets",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("policy_type", sa.String(length=20), nullable=False),
        sa.Column("target_amount_minor", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "policy_type", name="uq_insurance_targets_user_type"),
    )
    op.create_index(
        op.f("ix_insurance_targets_user_id"), "insurance_targets", ["user_id"], unique=False
    )
    op.create_table(
        "policies",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("policy_type", sa.String(length=20), nullable=False),
        sa.Column("provider", sa.String(length=200), nullable=False),
        sa.Column("coverage_amount_minor", sa.BigInteger(), nullable=False),
        sa.Column("premium_amount_minor", sa.BigInteger(), nullable=False),
        sa.Column("premium_frequency", sa.String(length=20), nullable=False),
        sa.Column("expiry_date", sa.String(length=10), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_policies_user_active", "policies", ["user_id", "is_active"], unique=False)
    op.create_index(op.f("ix_policies_user_id"), "policies", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_policies_user_id"), table_name="policies")
    op.drop_index("ix_policies_user_active", table_name="policies")
    op.drop_table("policies")
    op.drop_index(op.f("ix_insurance_targets_user_id"), table_name="insurance_targets")
    op.drop_table("insurance_targets")
    # ### end Alembic commands ###
