"""add fire_strategies table

Revision ID: 8abfcafaeff3
Revises: b1f2a3c4d5e6
Create Date: 2026-06-28 19:24:20.262570

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "8abfcafaeff3"
down_revision: Union[str, None] = "b1f2a3c4d5e6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fire_strategies",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("strategy", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_fire_strategies_user_id"), "fire_strategies", ["user_id"], unique=False
    )
    op.create_index(
        "ix_fire_strategies_user_version", "fire_strategies", ["user_id", "version"], unique=False
    )
    op.create_index(
        op.f("ix_advisory_reports_user_id"), "advisory_reports", ["user_id"], unique=False
    )
    op.create_index(op.f("ix_fi_goals_user_id"), "fi_goals", ["user_id"], unique=False)
    op.create_index(op.f("ix_fi_scores_user_id"), "fi_scores", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_fi_scores_user_id"), table_name="fi_scores")
    op.drop_index(op.f("ix_fi_goals_user_id"), table_name="fi_goals")
    op.drop_index(op.f("ix_advisory_reports_user_id"), table_name="advisory_reports")
    op.drop_index("ix_fire_strategies_user_version", table_name="fire_strategies")
    op.drop_index(op.f("ix_fire_strategies_user_id"), table_name="fire_strategies")
    op.drop_table("fire_strategies")
    # ### end Alembic commands ###
