"""add billing_cycle to subscriptions

Revision ID: a4c19f8b2e7d
Revises: 5000c0dcac6f
Create Date: 2026-07-29 10:24:11.402118

Hand-authored rather than autogenerated: autogenerate also wants to drop the
LangGraph checkpoint tables, which are managed by the checkpointer (see
7c5e28f749e7_add_billing_tables.py).

Originally authored against d902dbeff7d5, but 5000c0dcac6f (agent-session
persona) landed on the same parent while this branch was open. Two revisions
sharing a parent is two heads, and the API container runs `alembic upgrade
head` on boot (Dockerfile.api), so that would have failed the deploy outright
rather than degrading — re-pointed onto the persona revision to keep the chain
linear.
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a4c19f8b2e7d"
down_revision: Union[str, None] = "5000c0dcac6f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Nullable with no backfill: existing rows genuinely don't record which price
    # they were bought on, and inferring it from the period bounds would write a
    # guess the UI then presents as fact. They resolve on the next webhook.
    op.add_column(
        "subscriptions",
        sa.Column("billing_cycle", sa.String(length=10), nullable=True),
    )


def downgrade() -> None:
    op.drop_column("subscriptions", "billing_cycle")
