"""drop duplicate paddle_customer_id from user_profiles

Revision ID: b7d34e1c9a02
Revises: a4c19f8b2e7d
Create Date: 2026-07-29 10:31:52.774901

user_profiles.paddle_customer_id and subscriptions.provider_customer_id held the
same value, both written from the same webhook field. The subscription row is the
right home — it sits with provider and provider_subscription_id and is not
Paddle-specific — so the profile copy goes.

Hand-authored rather than autogenerated: autogenerate also wants to drop the
LangGraph checkpoint tables (see 7c5e28f749e7_add_billing_tables.py).
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b7d34e1c9a02"
down_revision: Union[str, None] = "a4c19f8b2e7d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Backfill before dropping. The two columns were written together, so they
    # should already agree, but a profile row can carry an id from a
    # transaction.completed event that landed before any subscription row existed.
    # Only fills NULLs — never overwrites what the subscription already claims.
    op.execute(
        """
        UPDATE subscriptions s
        SET provider_customer_id = p.paddle_customer_id
        FROM user_profiles p
        WHERE p.id = s.user_id
          AND s.provider_customer_id IS NULL
          AND p.paddle_customer_id IS NOT NULL
        """
    )
    op.drop_column("user_profiles", "paddle_customer_id")


def downgrade() -> None:
    op.add_column(
        "user_profiles",
        sa.Column("paddle_customer_id", sa.String(length=100), nullable=True),
    )
    op.execute(
        """
        UPDATE user_profiles p
        SET paddle_customer_id = s.provider_customer_id
        FROM subscriptions s
        WHERE s.user_id = p.id AND s.provider_customer_id IS NOT NULL
        """
    )
