"""initial_schema

Revision ID: d71db27e7d96
Revises:
Create Date: 2026-06-18 20:14:33.552664

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d71db27e7d96"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "accounts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("code", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("type", sa.String(length=20), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("parent_id", sa.String(length=36), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "type IN ('asset','liability','equity','income','expense')", name="ck_accounts_type"
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["accounts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "code", name="uq_accounts_user_code"),
    )
    op.create_index(op.f("ix_accounts_user_id"), "accounts", ["user_id"], unique=False)
    op.create_table(
        "documents",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("kind", sa.String(length=50), nullable=False),
        sa.Column("storage_key", sa.String(length=500), nullable=False),
        sa.Column("year", sa.String(length=10), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_documents_user_id"), "documents", ["user_id"], unique=False)
    op.create_table(
        "journal_entries",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("entry_date", sa.String(length=10), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("external_ref", sa.String(length=200), nullable=True),
        sa.Column("reversed_by", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "source IN ('manual','statement','sms','system')", name="ck_journal_entries_source"
        ),
        sa.ForeignKeyConstraint(
            ["reversed_by"],
            ["journal_entries.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_journal_entries_user_date", "journal_entries", ["user_id", "entry_date"], unique=False
    )
    op.create_index(
        op.f("ix_journal_entries_user_id"), "journal_entries", ["user_id"], unique=False
    )
    op.create_table(
        "reminders",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("due_date", sa.String(length=10), nullable=False),
        sa.Column("kind", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_reminders_user_id"), "reminders", ["user_id"], unique=False)
    op.create_table(
        "statements",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("storage_key", sa.String(length=500), nullable=False),
        sa.Column("bank", sa.String(length=100), nullable=True),
        sa.Column("period_start", sa.String(length=10), nullable=True),
        sa.Column("period_end", sa.String(length=10), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_statements_user_id"), "statements", ["user_id"], unique=False)
    op.create_table(
        "tax_computations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("year", sa.String(length=10), nullable=False),
        sa.Column("pack_version", sa.String(length=20), nullable=False),
        sa.Column("inputs_hash", sa.String(length=64), nullable=False),
        sa.Column("result_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_tax_computations_user_id"), "tax_computations", ["user_id"], unique=False
    )
    op.create_index(
        "ix_tax_computations_user_year", "tax_computations", ["user_id", "year"], unique=False
    )
    op.create_table(
        "parsed_transactions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("statement_id", sa.String(length=36), nullable=False),
        sa.Column("raw", sa.Text(), nullable=False),
        sa.Column("extracted_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=4, scale=3), nullable=True),
        sa.Column("dedup_key", sa.String(length=64), nullable=True),
        sa.Column("dedup_status", sa.String(length=20), nullable=False),
        sa.Column("posted_entry_id", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["posted_entry_id"],
            ["journal_entries.id"],
        ),
        sa.ForeignKeyConstraint(["statement_id"], ["statements.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_parsed_transactions_dedup_key"), "parsed_transactions", ["dedup_key"], unique=False
    )
    op.create_table(
        "postings",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("entry_id", sa.String(length=36), nullable=False),
        sa.Column("account_id", sa.String(length=36), nullable=False),
        sa.Column("direction", sa.Integer(), nullable=False),
        sa.Column("amount_minor", sa.BigInteger(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("fx_rate", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("fx_rate_source", sa.String(length=50), nullable=True),
        sa.Column("base_amount_minor", sa.BigInteger(), nullable=False),
        sa.CheckConstraint("amount_minor > 0", name="ck_postings_amount_positive"),
        sa.CheckConstraint("direction IN (1, -1)", name="ck_postings_direction"),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
        ),
        sa.ForeignKeyConstraint(["entry_id"], ["journal_entries.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_postings_account", "postings", ["account_id"], unique=False)
    op.create_index("ix_postings_entry", "postings", ["entry_id"], unique=False)
    # ### end Alembic commands ###

    # Double-entry balance constraint: sum(direction * base_amount_minor) per entry = 0.
    # Autogenerate cannot detect triggers; maintained manually here.
    # asyncpg requires each statement in its own execute() call.
    op.execute("""
        CREATE OR REPLACE FUNCTION check_entry_balance()
        RETURNS trigger LANGUAGE plpgsql AS $$
        DECLARE net BIGINT;
        BEGIN
            SELECT COALESCE(SUM(direction * base_amount_minor), 0)
              INTO net
              FROM postings
             WHERE entry_id = COALESCE(NEW.entry_id, OLD.entry_id);
            IF net <> 0 THEN
                RAISE EXCEPTION 'Unbalanced journal entry %: net = %',
                    COALESCE(NEW.entry_id, OLD.entry_id), net;
            END IF;
            RETURN NEW;
        END;
        $$
    """)
    op.execute("""
        CREATE CONSTRAINT TRIGGER trg_posting_balance
            AFTER INSERT OR UPDATE OR DELETE ON postings
            DEFERRABLE INITIALLY DEFERRED
            FOR EACH ROW EXECUTE FUNCTION check_entry_balance()
    """)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_postings_entry", table_name="postings")
    op.drop_index("ix_postings_account", table_name="postings")
    op.drop_table("postings")
    op.drop_index(op.f("ix_parsed_transactions_dedup_key"), table_name="parsed_transactions")
    op.drop_table("parsed_transactions")
    op.drop_index("ix_tax_computations_user_year", table_name="tax_computations")
    op.drop_index(op.f("ix_tax_computations_user_id"), table_name="tax_computations")
    op.drop_table("tax_computations")
    op.drop_index(op.f("ix_statements_user_id"), table_name="statements")
    op.drop_table("statements")
    op.drop_index(op.f("ix_reminders_user_id"), table_name="reminders")
    op.drop_table("reminders")
    op.drop_index(op.f("ix_journal_entries_user_id"), table_name="journal_entries")
    op.drop_index("ix_journal_entries_user_date", table_name="journal_entries")
    op.drop_table("journal_entries")
    op.drop_index(op.f("ix_documents_user_id"), table_name="documents")
    op.drop_table("documents")
    op.drop_index(op.f("ix_accounts_user_id"), table_name="accounts")
    op.drop_table("accounts")
    op.execute("DROP TRIGGER IF EXISTS trg_posting_balance ON postings")
    op.execute("DROP FUNCTION IF EXISTS check_entry_balance()")
    # ### end Alembic commands ###
