"""add alert fields to reminders table

Revision ID: e3198057dfb5
Revises: 5474ef0df2f2
Create Date: 2026-07-16 10:24:56.642414

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e3198057dfb5"
down_revision: Union[str, None] = "5474ef0df2f2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("reminders", sa.Column("alert_type", sa.String(length=40), nullable=True))
    op.add_column("reminders", sa.Column("source_domain", sa.String(length=40), nullable=True))
    op.add_column("reminders", sa.Column("source_id", sa.String(length=200), nullable=True))
    op.add_column("reminders", sa.Column("severity", sa.String(length=20), nullable=True))
    op.create_index(
        "ix_reminders_user_alert_source",
        "reminders",
        ["user_id", "source_domain", "source_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_reminders_user_alert_source", table_name="reminders")
    op.drop_column("reminders", "severity")
    op.drop_column("reminders", "source_id")
    op.drop_column("reminders", "source_domain")
    op.drop_column("reminders", "alert_type")
    # ### end Alembic commands ###
