"""add recurring_subscriptions table

Revision ID: e6cb7ee51794
Revises: 2c054a68f54e
Create Date: 2026-07-16 08:00:03.248208

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e6cb7ee51794"
down_revision: Union[str, None] = "2c054a68f54e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "recurring_subscriptions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("amount_minor", sa.BigInteger(), nullable=False),
        sa.Column("frequency", sa.String(length=20), nullable=False),
        sa.Column("next_due_date", sa.String(length=10), nullable=False),
        sa.Column("account_id", sa.String(length=36), nullable=True),
        sa.Column("grace_days", sa.Integer(), nullable=False),
        sa.Column("amount_tolerance_pct", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_recurring_subscriptions_user_active",
        "recurring_subscriptions",
        ["user_id", "is_active"],
        unique=False,
    )
    op.create_index(
        op.f("ix_recurring_subscriptions_user_id"),
        "recurring_subscriptions",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_recurring_subscriptions_user_id"), table_name="recurring_subscriptions")
    op.drop_index("ix_recurring_subscriptions_user_active", table_name="recurring_subscriptions")
    op.drop_table("recurring_subscriptions")
    # ### end Alembic commands ###
