"""add daily_briefing_enabled to user_profiles

Revision ID: e7b204c8a915
Revises: c3f81a2d9e44
Create Date: 2026-08-24 00:20:00.000000

The scheduled daily advisor run was gated on an active paid subscription. Tiers
now differ only in AI usage allowance, so the run is available on every plan —
but opt-in, because it spends the user's own advisor_runs quota. Defaulting it
on would silently consume a Free user's entire monthly allowance inside ten
days, before they had ever asked for a briefing.

Existing paid subscribers who were receiving the daily run are NOT backfilled to
True. That's deliberate: a silent opt-in is the thing this column exists to
prevent, and the toggle is one tap in Settings. Anyone who wants it back gets it
back knowingly.

Hand-authored rather than autogenerated: autogenerate also wants to drop the
LangGraph checkpoint tables, which are managed by the checkpointer (see
7c5e28f749e7_add_billing_tables.py).
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e7b204c8a915"
down_revision: Union[str, None] = "c3f81a2d9e44"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # server_default so the NOT NULL applies to existing rows, then dropped so
    # the application stays the single source of truth — same pattern
    # e0424fe3c976 used for mcp_enabled.
    op.add_column(
        "user_profiles",
        sa.Column(
            "daily_briefing_enabled",
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
    )
    op.alter_column("user_profiles", "daily_briefing_enabled", server_default=None)


def downgrade() -> None:
    op.drop_column("user_profiles", "daily_briefing_enabled")
