"""extend user_profiles with fact-find columns

Revision ID: fa523e86f4cf
Revises: 8abfcafaeff3
Create Date: 2026-07-15 20:43:57.013866

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fa523e86f4cf"
down_revision: Union[str, None] = "8abfcafaeff3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user_profiles", sa.Column("date_of_birth", sa.Date(), nullable=True))
    op.add_column("user_profiles", sa.Column("dependents_count", sa.Integer(), nullable=True))
    op.add_column(
        "user_profiles", sa.Column("employment_status", sa.String(length=32), nullable=True)
    )
    op.add_column(
        "user_profiles", sa.Column("residency_status", sa.String(length=32), nullable=True)
    )
    op.add_column("user_profiles", sa.Column("employer", sa.String(length=200), nullable=True))
    op.add_column(
        "user_profiles", sa.Column("employment_type", sa.String(length=32), nullable=True)
    )
    op.add_column("user_profiles", sa.Column("ird_number", sa.String(length=32), nullable=True))
    op.add_column("user_profiles", sa.Column("risk_score", sa.Integer(), nullable=True))
    op.add_column("user_profiles", sa.Column("risk_category", sa.String(length=16), nullable=True))
    op.add_column("user_profiles", sa.Column("life_stage", sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_profiles", "life_stage")
    op.drop_column("user_profiles", "risk_category")
    op.drop_column("user_profiles", "risk_score")
    op.drop_column("user_profiles", "ird_number")
    op.drop_column("user_profiles", "employment_type")
    op.drop_column("user_profiles", "employer")
    op.drop_column("user_profiles", "residency_status")
    op.drop_column("user_profiles", "employment_status")
    op.drop_column("user_profiles", "dependents_count")
    op.drop_column("user_profiles", "date_of_birth")
    # ### end Alembic commands ###
