// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getLogStream(args?: GetLogStreamArgs, opts?: pulumi.InvokeOptions): Promise<GetLogStreamResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("render:index/getLogStream:getLogStream", {
        "endpoint": args.endpoint,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getLogStream.
 */
export interface GetLogStreamArgs {
    endpoint?: string;
}

/**
 * A collection of values returned by getLogStream.
 */
export interface GetLogStreamResult {
    readonly endpoint?: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly preview: string;
}
export function getLogStreamOutput(args?: GetLogStreamOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetLogStreamResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("render:index/getLogStream:getLogStream", {
        "endpoint": args.endpoint,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getLogStream.
 */
export interface GetLogStreamOutputArgs {
    endpoint?: pulumi.Input<string | undefined>;
}
