// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getMetricsStream(opts?: pulumi.InvokeOptions): Promise<GetMetricsStreamResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("render:index/getMetricsStream:getMetricsStream", {
    }, opts, utilities.getPackage());
}

/**
 * A collection of values returned by getMetricsStream.
 */
export interface GetMetricsStreamResult {
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly metricsProvider: string;
    readonly url: string;
}
export function getMetricsStreamOutput(opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetMetricsStreamResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("render:index/getMetricsStream:getMetricsStream", {
    }, opts, utilities.getPackage());
}
