// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class LogStream extends pulumi.CustomResource {
    /**
     * Get an existing LogStream resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: LogStreamState, opts?: pulumi.CustomResourceOptions): LogStream {
        return new LogStream(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'render:index/logStream:LogStream';

    /**
     * Returns true if the given object is an instance of LogStream.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is LogStream {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === LogStream.__pulumiType;
    }

    /**
     * The endpoint to send logs to.
     */
    declare public readonly endpoint: pulumi.Output<string | undefined>;
    /**
     * Whether to send or drop logs for preview resources. Must be one of <span pulumi-lang-nodejs="`send`" pulumi-lang-dotnet="`Send`" pulumi-lang-go="`send`" pulumi-lang-python="`send`" pulumi-lang-yaml="`send`" pulumi-lang-java="`send`" pulumi-lang-hcl="`send`">`send`</span> or <span pulumi-lang-nodejs="`drop`" pulumi-lang-dotnet="`Drop`" pulumi-lang-go="`drop`" pulumi-lang-python="`drop`" pulumi-lang-yaml="`drop`" pulumi-lang-java="`drop`" pulumi-lang-hcl="`drop`">`drop`</span>.
     */
    declare public readonly preview: pulumi.Output<string>;
    /**
     * The token to use when sending logs.
     */
    declare public readonly token: pulumi.Output<string | undefined>;

    /**
     * Create a LogStream resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: LogStreamArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: LogStreamArgs | LogStreamState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as LogStreamState | undefined;
            resourceInputs["endpoint"] = state?.endpoint;
            resourceInputs["preview"] = state?.preview;
            resourceInputs["token"] = state?.token;
        } else {
            const args = argsOrState as LogStreamArgs | undefined;
            if (args?.preview === undefined && !opts.urn) {
                throw new Error("Missing required property 'preview'");
            }
            resourceInputs["endpoint"] = args?.endpoint;
            resourceInputs["preview"] = args?.preview;
            resourceInputs["token"] = args?.token ? pulumi.secret(args.token) : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["token"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(LogStream.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering LogStream resources.
 */
export interface LogStreamState {
    /**
     * The endpoint to send logs to.
     */
    endpoint?: pulumi.Input<string | undefined>;
    /**
     * Whether to send or drop logs for preview resources. Must be one of <span pulumi-lang-nodejs="`send`" pulumi-lang-dotnet="`Send`" pulumi-lang-go="`send`" pulumi-lang-python="`send`" pulumi-lang-yaml="`send`" pulumi-lang-java="`send`" pulumi-lang-hcl="`send`">`send`</span> or <span pulumi-lang-nodejs="`drop`" pulumi-lang-dotnet="`Drop`" pulumi-lang-go="`drop`" pulumi-lang-python="`drop`" pulumi-lang-yaml="`drop`" pulumi-lang-java="`drop`" pulumi-lang-hcl="`drop`">`drop`</span>.
     */
    preview?: pulumi.Input<string | undefined>;
    /**
     * The token to use when sending logs.
     */
    token?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a LogStream resource.
 */
export interface LogStreamArgs {
    /**
     * The endpoint to send logs to.
     */
    endpoint?: pulumi.Input<string | undefined>;
    /**
     * Whether to send or drop logs for preview resources. Must be one of <span pulumi-lang-nodejs="`send`" pulumi-lang-dotnet="`Send`" pulumi-lang-go="`send`" pulumi-lang-python="`send`" pulumi-lang-yaml="`send`" pulumi-lang-java="`send`" pulumi-lang-hcl="`send`">`send`</span> or <span pulumi-lang-nodejs="`drop`" pulumi-lang-dotnet="`Drop`" pulumi-lang-go="`drop`" pulumi-lang-python="`drop`" pulumi-lang-yaml="`drop`" pulumi-lang-java="`drop`" pulumi-lang-hcl="`drop`">`drop`</span>.
     */
    preview: pulumi.Input<string>;
    /**
     * The token to use when sending logs.
     */
    token?: pulumi.Input<string | undefined>;
}
