// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class PrivateService extends pulumi.CustomResource {
    /**
     * Get an existing PrivateService resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: PrivateServiceState, opts?: pulumi.CustomResourceOptions): PrivateService {
        return new PrivateService(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'render:index/privateService:PrivateService';

    /**
     * Returns true if the given object is an instance of PrivateService.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is PrivateService {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === PrivateService.__pulumiType;
    }

    /**
     * [Autoscaling settings](https://render.com/docs/scaling#autoscaling) for the service
     */
    declare public readonly autoscaling: pulumi.Output<outputs.PrivateServiceAutoscaling | undefined>;
    /**
     * [Persistent disk](https://render.com/docs/disks) to attach to the service.
     */
    declare public readonly disk: pulumi.Output<outputs.PrivateServiceDisk | undefined>;
    /**
     * Map of environment variable names to their values.
     */
    declare public readonly envVars: pulumi.Output<{[key: string]: outputs.PrivateServiceEnvVars} | undefined>;
    /**
     * ID of the [project environment](https://render.com/docs/projects) that the resource belongs to
     */
    declare public readonly environmentId: pulumi.Output<string | undefined>;
    /**
     * Configure the [log stream override settings](https://render.com/docs/log-streams#overriding-defaults) for this service. These will override the global log stream settings of the user or team.
     */
    declare public readonly logStreamOverride: pulumi.Output<outputs.PrivateServiceLogStreamOverride>;
    /**
     * The maximum amount of time (in seconds) that Render waits for your application process to exit gracefully after sending it a SIGTERM signal before sending a SIGKILL signal.
     */
    declare public readonly maxShutdownDelaySeconds: pulumi.Output<number>;
    /**
     * Name of the service
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * Configure the [notification settings](https://render.com/docs/notifications) for this service. These will override the global notification settings of the user or team.
     */
    declare public readonly notificationOverride: pulumi.Output<outputs.PrivateServiceNotificationOverride>;
    /**
     * Number of replicas of the service to run. Defaults to 1 on service creation and current instance count on update. If you want to manage the service's instance count outside Terraform, leave<span pulumi-lang-nodejs=" numInstances " pulumi-lang-dotnet=" NumInstances " pulumi-lang-go=" numInstances " pulumi-lang-python=" num_instances " pulumi-lang-yaml=" numInstances " pulumi-lang-java=" numInstances " pulumi-lang-hcl=" num_instances "> numInstances </span>unset.
     */
    declare public readonly numInstances: pulumi.Output<number>;
    /**
     * Plan to use for the service. Must be one of <span pulumi-lang-nodejs="`starter`" pulumi-lang-dotnet="`Starter`" pulumi-lang-go="`starter`" pulumi-lang-python="`starter`" pulumi-lang-yaml="`starter`" pulumi-lang-java="`starter`" pulumi-lang-hcl="`starter`">`starter`</span>, <span pulumi-lang-nodejs="`standard`" pulumi-lang-dotnet="`Standard`" pulumi-lang-go="`standard`" pulumi-lang-python="`standard`" pulumi-lang-yaml="`standard`" pulumi-lang-java="`standard`" pulumi-lang-hcl="`standard`">`standard`</span>, <span pulumi-lang-nodejs="`pro`" pulumi-lang-dotnet="`Pro`" pulumi-lang-go="`pro`" pulumi-lang-python="`pro`" pulumi-lang-yaml="`pro`" pulumi-lang-java="`pro`" pulumi-lang-hcl="`pro`">`pro`</span>, <span pulumi-lang-nodejs="`proPlus`" pulumi-lang-dotnet="`ProPlus`" pulumi-lang-go="`proPlus`" pulumi-lang-python="`pro_plus`" pulumi-lang-yaml="`proPlus`" pulumi-lang-java="`proPlus`" pulumi-lang-hcl="`pro_plus`">`proPlus`</span>, <span pulumi-lang-nodejs="`proMax`" pulumi-lang-dotnet="`ProMax`" pulumi-lang-go="`proMax`" pulumi-lang-python="`pro_max`" pulumi-lang-yaml="`proMax`" pulumi-lang-java="`proMax`" pulumi-lang-hcl="`pro_max`">`proMax`</span>, <span pulumi-lang-nodejs="`proUltra`" pulumi-lang-dotnet="`ProUltra`" pulumi-lang-go="`proUltra`" pulumi-lang-python="`pro_ultra`" pulumi-lang-yaml="`proUltra`" pulumi-lang-java="`proUltra`" pulumi-lang-hcl="`pro_ultra`">`proUltra`</span>, or a custom plan.
     */
    declare public readonly plan: pulumi.Output<string>;
    /**
     * This command runs before starting your service. It is typically used for tasks like running a database migration or uploading assets to a CDN.
     */
    declare public readonly preDeployCommand: pulumi.Output<string | undefined>;
    /**
     * [Pull request previews](https://render.com/docs/pull-request-previews#pull-request-previews-git-backed) settings
     */
    declare public readonly previews: pulumi.Output<outputs.PrivateServicePreviews>;
    /**
     * Enable [pull request previews](https://render.com/docs/pull-request-previews#pull-request-previews-git-backed) for the service.
     *
     * @deprecated Deprecated
     */
    declare public readonly pullRequestPreviewsEnabled: pulumi.Output<boolean>;
    /**
     * [Region](https://render.com/docs/regions) to deploy the service. One of <span pulumi-lang-nodejs="`frankfurt`" pulumi-lang-dotnet="`Frankfurt`" pulumi-lang-go="`frankfurt`" pulumi-lang-python="`frankfurt`" pulumi-lang-yaml="`frankfurt`" pulumi-lang-java="`frankfurt`" pulumi-lang-hcl="`frankfurt`">`frankfurt`</span>, <span pulumi-lang-nodejs="`ohio`" pulumi-lang-dotnet="`Ohio`" pulumi-lang-go="`ohio`" pulumi-lang-python="`ohio`" pulumi-lang-yaml="`ohio`" pulumi-lang-java="`ohio`" pulumi-lang-hcl="`ohio`">`ohio`</span>, <span pulumi-lang-nodejs="`oregon`" pulumi-lang-dotnet="`Oregon`" pulumi-lang-go="`oregon`" pulumi-lang-python="`oregon`" pulumi-lang-yaml="`oregon`" pulumi-lang-java="`oregon`" pulumi-lang-hcl="`oregon`">`oregon`</span>, <span pulumi-lang-nodejs="`singapore`" pulumi-lang-dotnet="`Singapore`" pulumi-lang-go="`singapore`" pulumi-lang-python="`singapore`" pulumi-lang-yaml="`singapore`" pulumi-lang-java="`singapore`" pulumi-lang-hcl="`singapore`">`singapore`</span>, <span pulumi-lang-nodejs="`virginia`" pulumi-lang-dotnet="`Virginia`" pulumi-lang-go="`virginia`" pulumi-lang-python="`virginia`" pulumi-lang-yaml="`virginia`" pulumi-lang-java="`virginia`" pulumi-lang-hcl="`virginia`">`virginia`</span>.
     */
    declare public readonly region: pulumi.Output<string>;
    /**
     * When you specify a [root directory](https://render.com/docs/monorepo-support#root-directory), Render runs all your commands in the specified directory and ignores changes outside the directory. Defaults to the repository root.
     */
    declare public readonly rootDirectory: pulumi.Output<string>;
    /**
     * Source of the build artifacts or image that run your service. You must provide one of <span pulumi-lang-nodejs="[nativeRuntime]" pulumi-lang-dotnet="[NativeRuntime]" pulumi-lang-go="[nativeRuntime]" pulumi-lang-python="[native_runtime]" pulumi-lang-yaml="[nativeRuntime]" pulumi-lang-java="[nativeRuntime]" pulumi-lang-hcl="[native_runtime]">[nativeRuntime]</span>(https://render.com/docs/native-runtimes), [docker](https://render.com/docs/docker), or [image](https://render.com/docs/deploy-an-image).
     */
    declare public readonly runtimeSource: pulumi.Output<outputs.PrivateServiceRuntimeSource>;
    /**
     * A map of secret file paths to their contents.
     */
    declare public readonly secretFiles: pulumi.Output<{[key: string]: outputs.PrivateServiceSecretFiles} | undefined>;
    /**
     * Unique slug for the service
     */
    declare public /*out*/ readonly slug: pulumi.Output<string>;
    /**
     * Command to run the service. When using native runtimes, this will be used as the start command and is required. For [Docker](https://render.com/docs/docker) and [image-backed](https://render.com/docs/deploy-an-image) services, this will override the default Docker command for the image.
     */
    declare public readonly startCommand: pulumi.Output<string | undefined>;
    /**
     * URL that the service is accessible from.
     */
    declare public /*out*/ readonly url: pulumi.Output<string>;

    /**
     * Create a PrivateService resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: PrivateServiceArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: PrivateServiceArgs | PrivateServiceState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as PrivateServiceState | undefined;
            resourceInputs["autoscaling"] = state?.autoscaling;
            resourceInputs["disk"] = state?.disk;
            resourceInputs["envVars"] = state?.envVars;
            resourceInputs["environmentId"] = state?.environmentId;
            resourceInputs["logStreamOverride"] = state?.logStreamOverride;
            resourceInputs["maxShutdownDelaySeconds"] = state?.maxShutdownDelaySeconds;
            resourceInputs["name"] = state?.name;
            resourceInputs["notificationOverride"] = state?.notificationOverride;
            resourceInputs["numInstances"] = state?.numInstances;
            resourceInputs["plan"] = state?.plan;
            resourceInputs["preDeployCommand"] = state?.preDeployCommand;
            resourceInputs["previews"] = state?.previews;
            resourceInputs["pullRequestPreviewsEnabled"] = state?.pullRequestPreviewsEnabled;
            resourceInputs["region"] = state?.region;
            resourceInputs["rootDirectory"] = state?.rootDirectory;
            resourceInputs["runtimeSource"] = state?.runtimeSource;
            resourceInputs["secretFiles"] = state?.secretFiles;
            resourceInputs["slug"] = state?.slug;
            resourceInputs["startCommand"] = state?.startCommand;
            resourceInputs["url"] = state?.url;
        } else {
            const args = argsOrState as PrivateServiceArgs | undefined;
            if (args?.plan === undefined && !opts.urn) {
                throw new Error("Missing required property 'plan'");
            }
            if (args?.region === undefined && !opts.urn) {
                throw new Error("Missing required property 'region'");
            }
            if (args?.runtimeSource === undefined && !opts.urn) {
                throw new Error("Missing required property 'runtimeSource'");
            }
            resourceInputs["autoscaling"] = args?.autoscaling;
            resourceInputs["disk"] = args?.disk;
            resourceInputs["envVars"] = args?.envVars;
            resourceInputs["environmentId"] = args?.environmentId;
            resourceInputs["logStreamOverride"] = args?.logStreamOverride;
            resourceInputs["maxShutdownDelaySeconds"] = args?.maxShutdownDelaySeconds;
            resourceInputs["name"] = args?.name;
            resourceInputs["notificationOverride"] = args?.notificationOverride;
            resourceInputs["numInstances"] = args?.numInstances;
            resourceInputs["plan"] = args?.plan;
            resourceInputs["preDeployCommand"] = args?.preDeployCommand;
            resourceInputs["previews"] = args?.previews;
            resourceInputs["pullRequestPreviewsEnabled"] = args?.pullRequestPreviewsEnabled;
            resourceInputs["region"] = args?.region;
            resourceInputs["rootDirectory"] = args?.rootDirectory;
            resourceInputs["runtimeSource"] = args?.runtimeSource;
            resourceInputs["secretFiles"] = args?.secretFiles;
            resourceInputs["startCommand"] = args?.startCommand;
            resourceInputs["slug"] = undefined /*out*/;
            resourceInputs["url"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(PrivateService.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering PrivateService resources.
 */
export interface PrivateServiceState {
    /**
     * [Autoscaling settings](https://render.com/docs/scaling#autoscaling) for the service
     */
    autoscaling?: pulumi.Input<inputs.PrivateServiceAutoscaling | undefined>;
    /**
     * [Persistent disk](https://render.com/docs/disks) to attach to the service.
     */
    disk?: pulumi.Input<inputs.PrivateServiceDisk | undefined>;
    /**
     * Map of environment variable names to their values.
     */
    envVars?: pulumi.Input<{[key: string]: pulumi.Input<inputs.PrivateServiceEnvVars>} | undefined>;
    /**
     * ID of the [project environment](https://render.com/docs/projects) that the resource belongs to
     */
    environmentId?: pulumi.Input<string | undefined>;
    /**
     * Configure the [log stream override settings](https://render.com/docs/log-streams#overriding-defaults) for this service. These will override the global log stream settings of the user or team.
     */
    logStreamOverride?: pulumi.Input<inputs.PrivateServiceLogStreamOverride | undefined>;
    /**
     * The maximum amount of time (in seconds) that Render waits for your application process to exit gracefully after sending it a SIGTERM signal before sending a SIGKILL signal.
     */
    maxShutdownDelaySeconds?: pulumi.Input<number | undefined>;
    /**
     * Name of the service
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * Configure the [notification settings](https://render.com/docs/notifications) for this service. These will override the global notification settings of the user or team.
     */
    notificationOverride?: pulumi.Input<inputs.PrivateServiceNotificationOverride | undefined>;
    /**
     * Number of replicas of the service to run. Defaults to 1 on service creation and current instance count on update. If you want to manage the service's instance count outside Terraform, leave<span pulumi-lang-nodejs=" numInstances " pulumi-lang-dotnet=" NumInstances " pulumi-lang-go=" numInstances " pulumi-lang-python=" num_instances " pulumi-lang-yaml=" numInstances " pulumi-lang-java=" numInstances " pulumi-lang-hcl=" num_instances "> numInstances </span>unset.
     */
    numInstances?: pulumi.Input<number | undefined>;
    /**
     * Plan to use for the service. Must be one of <span pulumi-lang-nodejs="`starter`" pulumi-lang-dotnet="`Starter`" pulumi-lang-go="`starter`" pulumi-lang-python="`starter`" pulumi-lang-yaml="`starter`" pulumi-lang-java="`starter`" pulumi-lang-hcl="`starter`">`starter`</span>, <span pulumi-lang-nodejs="`standard`" pulumi-lang-dotnet="`Standard`" pulumi-lang-go="`standard`" pulumi-lang-python="`standard`" pulumi-lang-yaml="`standard`" pulumi-lang-java="`standard`" pulumi-lang-hcl="`standard`">`standard`</span>, <span pulumi-lang-nodejs="`pro`" pulumi-lang-dotnet="`Pro`" pulumi-lang-go="`pro`" pulumi-lang-python="`pro`" pulumi-lang-yaml="`pro`" pulumi-lang-java="`pro`" pulumi-lang-hcl="`pro`">`pro`</span>, <span pulumi-lang-nodejs="`proPlus`" pulumi-lang-dotnet="`ProPlus`" pulumi-lang-go="`proPlus`" pulumi-lang-python="`pro_plus`" pulumi-lang-yaml="`proPlus`" pulumi-lang-java="`proPlus`" pulumi-lang-hcl="`pro_plus`">`proPlus`</span>, <span pulumi-lang-nodejs="`proMax`" pulumi-lang-dotnet="`ProMax`" pulumi-lang-go="`proMax`" pulumi-lang-python="`pro_max`" pulumi-lang-yaml="`proMax`" pulumi-lang-java="`proMax`" pulumi-lang-hcl="`pro_max`">`proMax`</span>, <span pulumi-lang-nodejs="`proUltra`" pulumi-lang-dotnet="`ProUltra`" pulumi-lang-go="`proUltra`" pulumi-lang-python="`pro_ultra`" pulumi-lang-yaml="`proUltra`" pulumi-lang-java="`proUltra`" pulumi-lang-hcl="`pro_ultra`">`proUltra`</span>, or a custom plan.
     */
    plan?: pulumi.Input<string | undefined>;
    /**
     * This command runs before starting your service. It is typically used for tasks like running a database migration or uploading assets to a CDN.
     */
    preDeployCommand?: pulumi.Input<string | undefined>;
    /**
     * [Pull request previews](https://render.com/docs/pull-request-previews#pull-request-previews-git-backed) settings
     */
    previews?: pulumi.Input<inputs.PrivateServicePreviews | undefined>;
    /**
     * Enable [pull request previews](https://render.com/docs/pull-request-previews#pull-request-previews-git-backed) for the service.
     *
     * @deprecated Deprecated
     */
    pullRequestPreviewsEnabled?: pulumi.Input<boolean | undefined>;
    /**
     * [Region](https://render.com/docs/regions) to deploy the service. One of <span pulumi-lang-nodejs="`frankfurt`" pulumi-lang-dotnet="`Frankfurt`" pulumi-lang-go="`frankfurt`" pulumi-lang-python="`frankfurt`" pulumi-lang-yaml="`frankfurt`" pulumi-lang-java="`frankfurt`" pulumi-lang-hcl="`frankfurt`">`frankfurt`</span>, <span pulumi-lang-nodejs="`ohio`" pulumi-lang-dotnet="`Ohio`" pulumi-lang-go="`ohio`" pulumi-lang-python="`ohio`" pulumi-lang-yaml="`ohio`" pulumi-lang-java="`ohio`" pulumi-lang-hcl="`ohio`">`ohio`</span>, <span pulumi-lang-nodejs="`oregon`" pulumi-lang-dotnet="`Oregon`" pulumi-lang-go="`oregon`" pulumi-lang-python="`oregon`" pulumi-lang-yaml="`oregon`" pulumi-lang-java="`oregon`" pulumi-lang-hcl="`oregon`">`oregon`</span>, <span pulumi-lang-nodejs="`singapore`" pulumi-lang-dotnet="`Singapore`" pulumi-lang-go="`singapore`" pulumi-lang-python="`singapore`" pulumi-lang-yaml="`singapore`" pulumi-lang-java="`singapore`" pulumi-lang-hcl="`singapore`">`singapore`</span>, <span pulumi-lang-nodejs="`virginia`" pulumi-lang-dotnet="`Virginia`" pulumi-lang-go="`virginia`" pulumi-lang-python="`virginia`" pulumi-lang-yaml="`virginia`" pulumi-lang-java="`virginia`" pulumi-lang-hcl="`virginia`">`virginia`</span>.
     */
    region?: pulumi.Input<string | undefined>;
    /**
     * When you specify a [root directory](https://render.com/docs/monorepo-support#root-directory), Render runs all your commands in the specified directory and ignores changes outside the directory. Defaults to the repository root.
     */
    rootDirectory?: pulumi.Input<string | undefined>;
    /**
     * Source of the build artifacts or image that run your service. You must provide one of <span pulumi-lang-nodejs="[nativeRuntime]" pulumi-lang-dotnet="[NativeRuntime]" pulumi-lang-go="[nativeRuntime]" pulumi-lang-python="[native_runtime]" pulumi-lang-yaml="[nativeRuntime]" pulumi-lang-java="[nativeRuntime]" pulumi-lang-hcl="[native_runtime]">[nativeRuntime]</span>(https://render.com/docs/native-runtimes), [docker](https://render.com/docs/docker), or [image](https://render.com/docs/deploy-an-image).
     */
    runtimeSource?: pulumi.Input<inputs.PrivateServiceRuntimeSource | undefined>;
    /**
     * A map of secret file paths to their contents.
     */
    secretFiles?: pulumi.Input<{[key: string]: pulumi.Input<inputs.PrivateServiceSecretFiles>} | undefined>;
    /**
     * Unique slug for the service
     */
    slug?: pulumi.Input<string | undefined>;
    /**
     * Command to run the service. When using native runtimes, this will be used as the start command and is required. For [Docker](https://render.com/docs/docker) and [image-backed](https://render.com/docs/deploy-an-image) services, this will override the default Docker command for the image.
     */
    startCommand?: pulumi.Input<string | undefined>;
    /**
     * URL that the service is accessible from.
     */
    url?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a PrivateService resource.
 */
export interface PrivateServiceArgs {
    /**
     * [Autoscaling settings](https://render.com/docs/scaling#autoscaling) for the service
     */
    autoscaling?: pulumi.Input<inputs.PrivateServiceAutoscaling | undefined>;
    /**
     * [Persistent disk](https://render.com/docs/disks) to attach to the service.
     */
    disk?: pulumi.Input<inputs.PrivateServiceDisk | undefined>;
    /**
     * Map of environment variable names to their values.
     */
    envVars?: pulumi.Input<{[key: string]: pulumi.Input<inputs.PrivateServiceEnvVars>} | undefined>;
    /**
     * ID of the [project environment](https://render.com/docs/projects) that the resource belongs to
     */
    environmentId?: pulumi.Input<string | undefined>;
    /**
     * Configure the [log stream override settings](https://render.com/docs/log-streams#overriding-defaults) for this service. These will override the global log stream settings of the user or team.
     */
    logStreamOverride?: pulumi.Input<inputs.PrivateServiceLogStreamOverride | undefined>;
    /**
     * The maximum amount of time (in seconds) that Render waits for your application process to exit gracefully after sending it a SIGTERM signal before sending a SIGKILL signal.
     */
    maxShutdownDelaySeconds?: pulumi.Input<number | undefined>;
    /**
     * Name of the service
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * Configure the [notification settings](https://render.com/docs/notifications) for this service. These will override the global notification settings of the user or team.
     */
    notificationOverride?: pulumi.Input<inputs.PrivateServiceNotificationOverride | undefined>;
    /**
     * Number of replicas of the service to run. Defaults to 1 on service creation and current instance count on update. If you want to manage the service's instance count outside Terraform, leave<span pulumi-lang-nodejs=" numInstances " pulumi-lang-dotnet=" NumInstances " pulumi-lang-go=" numInstances " pulumi-lang-python=" num_instances " pulumi-lang-yaml=" numInstances " pulumi-lang-java=" numInstances " pulumi-lang-hcl=" num_instances "> numInstances </span>unset.
     */
    numInstances?: pulumi.Input<number | undefined>;
    /**
     * Plan to use for the service. Must be one of <span pulumi-lang-nodejs="`starter`" pulumi-lang-dotnet="`Starter`" pulumi-lang-go="`starter`" pulumi-lang-python="`starter`" pulumi-lang-yaml="`starter`" pulumi-lang-java="`starter`" pulumi-lang-hcl="`starter`">`starter`</span>, <span pulumi-lang-nodejs="`standard`" pulumi-lang-dotnet="`Standard`" pulumi-lang-go="`standard`" pulumi-lang-python="`standard`" pulumi-lang-yaml="`standard`" pulumi-lang-java="`standard`" pulumi-lang-hcl="`standard`">`standard`</span>, <span pulumi-lang-nodejs="`pro`" pulumi-lang-dotnet="`Pro`" pulumi-lang-go="`pro`" pulumi-lang-python="`pro`" pulumi-lang-yaml="`pro`" pulumi-lang-java="`pro`" pulumi-lang-hcl="`pro`">`pro`</span>, <span pulumi-lang-nodejs="`proPlus`" pulumi-lang-dotnet="`ProPlus`" pulumi-lang-go="`proPlus`" pulumi-lang-python="`pro_plus`" pulumi-lang-yaml="`proPlus`" pulumi-lang-java="`proPlus`" pulumi-lang-hcl="`pro_plus`">`proPlus`</span>, <span pulumi-lang-nodejs="`proMax`" pulumi-lang-dotnet="`ProMax`" pulumi-lang-go="`proMax`" pulumi-lang-python="`pro_max`" pulumi-lang-yaml="`proMax`" pulumi-lang-java="`proMax`" pulumi-lang-hcl="`pro_max`">`proMax`</span>, <span pulumi-lang-nodejs="`proUltra`" pulumi-lang-dotnet="`ProUltra`" pulumi-lang-go="`proUltra`" pulumi-lang-python="`pro_ultra`" pulumi-lang-yaml="`proUltra`" pulumi-lang-java="`proUltra`" pulumi-lang-hcl="`pro_ultra`">`proUltra`</span>, or a custom plan.
     */
    plan: pulumi.Input<string>;
    /**
     * This command runs before starting your service. It is typically used for tasks like running a database migration or uploading assets to a CDN.
     */
    preDeployCommand?: pulumi.Input<string | undefined>;
    /**
     * [Pull request previews](https://render.com/docs/pull-request-previews#pull-request-previews-git-backed) settings
     */
    previews?: pulumi.Input<inputs.PrivateServicePreviews | undefined>;
    /**
     * Enable [pull request previews](https://render.com/docs/pull-request-previews#pull-request-previews-git-backed) for the service.
     *
     * @deprecated Deprecated
     */
    pullRequestPreviewsEnabled?: pulumi.Input<boolean | undefined>;
    /**
     * [Region](https://render.com/docs/regions) to deploy the service. One of <span pulumi-lang-nodejs="`frankfurt`" pulumi-lang-dotnet="`Frankfurt`" pulumi-lang-go="`frankfurt`" pulumi-lang-python="`frankfurt`" pulumi-lang-yaml="`frankfurt`" pulumi-lang-java="`frankfurt`" pulumi-lang-hcl="`frankfurt`">`frankfurt`</span>, <span pulumi-lang-nodejs="`ohio`" pulumi-lang-dotnet="`Ohio`" pulumi-lang-go="`ohio`" pulumi-lang-python="`ohio`" pulumi-lang-yaml="`ohio`" pulumi-lang-java="`ohio`" pulumi-lang-hcl="`ohio`">`ohio`</span>, <span pulumi-lang-nodejs="`oregon`" pulumi-lang-dotnet="`Oregon`" pulumi-lang-go="`oregon`" pulumi-lang-python="`oregon`" pulumi-lang-yaml="`oregon`" pulumi-lang-java="`oregon`" pulumi-lang-hcl="`oregon`">`oregon`</span>, <span pulumi-lang-nodejs="`singapore`" pulumi-lang-dotnet="`Singapore`" pulumi-lang-go="`singapore`" pulumi-lang-python="`singapore`" pulumi-lang-yaml="`singapore`" pulumi-lang-java="`singapore`" pulumi-lang-hcl="`singapore`">`singapore`</span>, <span pulumi-lang-nodejs="`virginia`" pulumi-lang-dotnet="`Virginia`" pulumi-lang-go="`virginia`" pulumi-lang-python="`virginia`" pulumi-lang-yaml="`virginia`" pulumi-lang-java="`virginia`" pulumi-lang-hcl="`virginia`">`virginia`</span>.
     */
    region: pulumi.Input<string>;
    /**
     * When you specify a [root directory](https://render.com/docs/monorepo-support#root-directory), Render runs all your commands in the specified directory and ignores changes outside the directory. Defaults to the repository root.
     */
    rootDirectory?: pulumi.Input<string | undefined>;
    /**
     * Source of the build artifacts or image that run your service. You must provide one of <span pulumi-lang-nodejs="[nativeRuntime]" pulumi-lang-dotnet="[NativeRuntime]" pulumi-lang-go="[nativeRuntime]" pulumi-lang-python="[native_runtime]" pulumi-lang-yaml="[nativeRuntime]" pulumi-lang-java="[nativeRuntime]" pulumi-lang-hcl="[native_runtime]">[nativeRuntime]</span>(https://render.com/docs/native-runtimes), [docker](https://render.com/docs/docker), or [image](https://render.com/docs/deploy-an-image).
     */
    runtimeSource: pulumi.Input<inputs.PrivateServiceRuntimeSource>;
    /**
     * A map of secret file paths to their contents.
     */
    secretFiles?: pulumi.Input<{[key: string]: pulumi.Input<inputs.PrivateServiceSecretFiles>} | undefined>;
    /**
     * Command to run the service. When using native runtimes, this will be used as the start command and is required. For [Docker](https://render.com/docs/docker) and [image-backed](https://render.com/docs/deploy-an-image) services, this will override the default Docker command for the image.
     */
    startCommand?: pulumi.Input<string | undefined>;
}
