// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class StaticSite extends pulumi.CustomResource {
    /**
     * Get an existing StaticSite resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: StaticSiteState, opts?: pulumi.CustomResourceOptions): StaticSite {
        return new StaticSite(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'render:index/staticSite:StaticSite';

    /**
     * Returns true if the given object is an instance of StaticSite.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is StaticSite {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === StaticSite.__pulumiType;
    }

    /**
     * All active custom domains associated with the service, including any auto-generated redirect domains.
     */
    declare public /*out*/ readonly activeCustomDomains: pulumi.Output<outputs.StaticSiteActiveCustomDomain[]>;
    /**
     * [Automatic deploy](https://render.com/docs/deploys#automatic-git-deploys) on every push to your repository, or changes to your service settings or environment.
     */
    declare public readonly autoDeploy: pulumi.Output<boolean>;
    /**
     * Sets the Automatic deploy behavior for a Git-based service.
     */
    declare public readonly autoDeployTrigger: pulumi.Output<string>;
    /**
     * Branch of the git repository to build.
     */
    declare public readonly branch: pulumi.Output<string>;
    /**
     * Command to build the service
     */
    declare public readonly buildCommand: pulumi.Output<string>;
    /**
     * Apply [build filters](https://render.com/docs/monorepo-support#build-filters) to configure which changes in your git repository trigger automatic deploys. If you've defined a root directory, you can still define paths outside of the root directory.
     */
    declare public readonly buildFilter: pulumi.Output<outputs.StaticSiteBuildFilter | undefined>;
    /**
     * Custom domains to associate with the service.
     */
    declare public readonly customDomains: pulumi.Output<outputs.StaticSiteCustomDomain[] | undefined>;
    /**
     * Map of environment variable names to their values.
     */
    declare public readonly envVars: pulumi.Output<{[key: string]: outputs.StaticSiteEnvVars} | undefined>;
    /**
     * ID of the [project environment](https://render.com/docs/projects) that the resource belongs to
     */
    declare public readonly environmentId: pulumi.Output<string | undefined>;
    /**
     * List of [headers](https://render.com/docs/static-site-headers) to apply to requests for static sites
     */
    declare public readonly headers: pulumi.Output<outputs.StaticSiteHeader[] | undefined>;
    /**
     * List of IP addresses that are allowed to connect to the web service. If omitted, the API default (0.0.0.0/0 - allow all) is used. If set to an empty list, all traffic is blocked. If removed after being set, it reverts to the default (0.0.0.0/0). This is an enterprise-only feature.
     */
    declare public readonly ipAllowLists: pulumi.Output<outputs.StaticSiteIpAllowList[] | undefined>;
    /**
     * Name of the service
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * Configure the [notification settings](https://render.com/docs/notifications) for this service. These will override the global notification settings of the user or team.
     */
    declare public readonly notificationOverride: pulumi.Output<outputs.StaticSiteNotificationOverride>;
    /**
     * [Pull request previews](https://render.com/docs/pull-request-previews#pull-request-previews-git-backed) settings
     */
    declare public readonly previews: pulumi.Output<outputs.StaticSitePreviews>;
    /**
     * Path to the directory that contains the build artifacts to publish for a static site. Defaults to public/.
     */
    declare public readonly publishPath: pulumi.Output<string>;
    /**
     * Enable [pull request previews](https://render.com/docs/pull-request-previews#pull-request-previews-git-backed) for the service.
     *
     * @deprecated Deprecated
     */
    declare public readonly pullRequestPreviewsEnabled: pulumi.Output<boolean>;
    /**
     * URL of the git repository to build.
     */
    declare public readonly repoUrl: pulumi.Output<string>;
    /**
     * When you specify a [root directory](https://render.com/docs/monorepo-support#root-directory), Render runs all your commands in the specified directory and ignores changes outside the directory. Defaults to the repository root.
     */
    declare public readonly rootDirectory: pulumi.Output<string>;
    /**
     * List of [redirect and rewrite rules](https://render.com/docs/redirects-rewrites) to apply to a static site.
     */
    declare public readonly routes: pulumi.Output<outputs.StaticSiteRoute[] | undefined>;
    /**
     * Unique slug for the service
     */
    declare public /*out*/ readonly slug: pulumi.Output<string>;
    /**
     * URL that the service is accessible from.
     */
    declare public /*out*/ readonly url: pulumi.Output<string>;

    /**
     * Create a StaticSite resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: StaticSiteArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: StaticSiteArgs | StaticSiteState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as StaticSiteState | undefined;
            resourceInputs["activeCustomDomains"] = state?.activeCustomDomains;
            resourceInputs["autoDeploy"] = state?.autoDeploy;
            resourceInputs["autoDeployTrigger"] = state?.autoDeployTrigger;
            resourceInputs["branch"] = state?.branch;
            resourceInputs["buildCommand"] = state?.buildCommand;
            resourceInputs["buildFilter"] = state?.buildFilter;
            resourceInputs["customDomains"] = state?.customDomains;
            resourceInputs["envVars"] = state?.envVars;
            resourceInputs["environmentId"] = state?.environmentId;
            resourceInputs["headers"] = state?.headers;
            resourceInputs["ipAllowLists"] = state?.ipAllowLists;
            resourceInputs["name"] = state?.name;
            resourceInputs["notificationOverride"] = state?.notificationOverride;
            resourceInputs["previews"] = state?.previews;
            resourceInputs["publishPath"] = state?.publishPath;
            resourceInputs["pullRequestPreviewsEnabled"] = state?.pullRequestPreviewsEnabled;
            resourceInputs["repoUrl"] = state?.repoUrl;
            resourceInputs["rootDirectory"] = state?.rootDirectory;
            resourceInputs["routes"] = state?.routes;
            resourceInputs["slug"] = state?.slug;
            resourceInputs["url"] = state?.url;
        } else {
            const args = argsOrState as StaticSiteArgs | undefined;
            if (args?.branch === undefined && !opts.urn) {
                throw new Error("Missing required property 'branch'");
            }
            if (args?.buildCommand === undefined && !opts.urn) {
                throw new Error("Missing required property 'buildCommand'");
            }
            if (args?.repoUrl === undefined && !opts.urn) {
                throw new Error("Missing required property 'repoUrl'");
            }
            resourceInputs["autoDeploy"] = args?.autoDeploy;
            resourceInputs["autoDeployTrigger"] = args?.autoDeployTrigger;
            resourceInputs["branch"] = args?.branch;
            resourceInputs["buildCommand"] = args?.buildCommand;
            resourceInputs["buildFilter"] = args?.buildFilter;
            resourceInputs["customDomains"] = args?.customDomains;
            resourceInputs["envVars"] = args?.envVars;
            resourceInputs["environmentId"] = args?.environmentId;
            resourceInputs["headers"] = args?.headers;
            resourceInputs["ipAllowLists"] = args?.ipAllowLists;
            resourceInputs["name"] = args?.name;
            resourceInputs["notificationOverride"] = args?.notificationOverride;
            resourceInputs["previews"] = args?.previews;
            resourceInputs["publishPath"] = args?.publishPath;
            resourceInputs["pullRequestPreviewsEnabled"] = args?.pullRequestPreviewsEnabled;
            resourceInputs["repoUrl"] = args?.repoUrl;
            resourceInputs["rootDirectory"] = args?.rootDirectory;
            resourceInputs["routes"] = args?.routes;
            resourceInputs["activeCustomDomains"] = undefined /*out*/;
            resourceInputs["slug"] = undefined /*out*/;
            resourceInputs["url"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(StaticSite.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering StaticSite resources.
 */
export interface StaticSiteState {
    /**
     * All active custom domains associated with the service, including any auto-generated redirect domains.
     */
    activeCustomDomains?: pulumi.Input<pulumi.Input<inputs.StaticSiteActiveCustomDomain>[] | undefined>;
    /**
     * [Automatic deploy](https://render.com/docs/deploys#automatic-git-deploys) on every push to your repository, or changes to your service settings or environment.
     */
    autoDeploy?: pulumi.Input<boolean | undefined>;
    /**
     * Sets the Automatic deploy behavior for a Git-based service.
     */
    autoDeployTrigger?: pulumi.Input<string | undefined>;
    /**
     * Branch of the git repository to build.
     */
    branch?: pulumi.Input<string | undefined>;
    /**
     * Command to build the service
     */
    buildCommand?: pulumi.Input<string | undefined>;
    /**
     * Apply [build filters](https://render.com/docs/monorepo-support#build-filters) to configure which changes in your git repository trigger automatic deploys. If you've defined a root directory, you can still define paths outside of the root directory.
     */
    buildFilter?: pulumi.Input<inputs.StaticSiteBuildFilter | undefined>;
    /**
     * Custom domains to associate with the service.
     */
    customDomains?: pulumi.Input<pulumi.Input<inputs.StaticSiteCustomDomain>[] | undefined>;
    /**
     * Map of environment variable names to their values.
     */
    envVars?: pulumi.Input<{[key: string]: pulumi.Input<inputs.StaticSiteEnvVars>} | undefined>;
    /**
     * ID of the [project environment](https://render.com/docs/projects) that the resource belongs to
     */
    environmentId?: pulumi.Input<string | undefined>;
    /**
     * List of [headers](https://render.com/docs/static-site-headers) to apply to requests for static sites
     */
    headers?: pulumi.Input<pulumi.Input<inputs.StaticSiteHeader>[] | undefined>;
    /**
     * List of IP addresses that are allowed to connect to the web service. If omitted, the API default (0.0.0.0/0 - allow all) is used. If set to an empty list, all traffic is blocked. If removed after being set, it reverts to the default (0.0.0.0/0). This is an enterprise-only feature.
     */
    ipAllowLists?: pulumi.Input<pulumi.Input<inputs.StaticSiteIpAllowList>[] | undefined>;
    /**
     * Name of the service
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * Configure the [notification settings](https://render.com/docs/notifications) for this service. These will override the global notification settings of the user or team.
     */
    notificationOverride?: pulumi.Input<inputs.StaticSiteNotificationOverride | undefined>;
    /**
     * [Pull request previews](https://render.com/docs/pull-request-previews#pull-request-previews-git-backed) settings
     */
    previews?: pulumi.Input<inputs.StaticSitePreviews | undefined>;
    /**
     * Path to the directory that contains the build artifacts to publish for a static site. Defaults to public/.
     */
    publishPath?: pulumi.Input<string | undefined>;
    /**
     * Enable [pull request previews](https://render.com/docs/pull-request-previews#pull-request-previews-git-backed) for the service.
     *
     * @deprecated Deprecated
     */
    pullRequestPreviewsEnabled?: pulumi.Input<boolean | undefined>;
    /**
     * URL of the git repository to build.
     */
    repoUrl?: pulumi.Input<string | undefined>;
    /**
     * When you specify a [root directory](https://render.com/docs/monorepo-support#root-directory), Render runs all your commands in the specified directory and ignores changes outside the directory. Defaults to the repository root.
     */
    rootDirectory?: pulumi.Input<string | undefined>;
    /**
     * List of [redirect and rewrite rules](https://render.com/docs/redirects-rewrites) to apply to a static site.
     */
    routes?: pulumi.Input<pulumi.Input<inputs.StaticSiteRoute>[] | undefined>;
    /**
     * Unique slug for the service
     */
    slug?: pulumi.Input<string | undefined>;
    /**
     * URL that the service is accessible from.
     */
    url?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a StaticSite resource.
 */
export interface StaticSiteArgs {
    /**
     * [Automatic deploy](https://render.com/docs/deploys#automatic-git-deploys) on every push to your repository, or changes to your service settings or environment.
     */
    autoDeploy?: pulumi.Input<boolean | undefined>;
    /**
     * Sets the Automatic deploy behavior for a Git-based service.
     */
    autoDeployTrigger?: pulumi.Input<string | undefined>;
    /**
     * Branch of the git repository to build.
     */
    branch: pulumi.Input<string>;
    /**
     * Command to build the service
     */
    buildCommand: pulumi.Input<string>;
    /**
     * Apply [build filters](https://render.com/docs/monorepo-support#build-filters) to configure which changes in your git repository trigger automatic deploys. If you've defined a root directory, you can still define paths outside of the root directory.
     */
    buildFilter?: pulumi.Input<inputs.StaticSiteBuildFilter | undefined>;
    /**
     * Custom domains to associate with the service.
     */
    customDomains?: pulumi.Input<pulumi.Input<inputs.StaticSiteCustomDomain>[] | undefined>;
    /**
     * Map of environment variable names to their values.
     */
    envVars?: pulumi.Input<{[key: string]: pulumi.Input<inputs.StaticSiteEnvVars>} | undefined>;
    /**
     * ID of the [project environment](https://render.com/docs/projects) that the resource belongs to
     */
    environmentId?: pulumi.Input<string | undefined>;
    /**
     * List of [headers](https://render.com/docs/static-site-headers) to apply to requests for static sites
     */
    headers?: pulumi.Input<pulumi.Input<inputs.StaticSiteHeader>[] | undefined>;
    /**
     * List of IP addresses that are allowed to connect to the web service. If omitted, the API default (0.0.0.0/0 - allow all) is used. If set to an empty list, all traffic is blocked. If removed after being set, it reverts to the default (0.0.0.0/0). This is an enterprise-only feature.
     */
    ipAllowLists?: pulumi.Input<pulumi.Input<inputs.StaticSiteIpAllowList>[] | undefined>;
    /**
     * Name of the service
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * Configure the [notification settings](https://render.com/docs/notifications) for this service. These will override the global notification settings of the user or team.
     */
    notificationOverride?: pulumi.Input<inputs.StaticSiteNotificationOverride | undefined>;
    /**
     * [Pull request previews](https://render.com/docs/pull-request-previews#pull-request-previews-git-backed) settings
     */
    previews?: pulumi.Input<inputs.StaticSitePreviews | undefined>;
    /**
     * Path to the directory that contains the build artifacts to publish for a static site. Defaults to public/.
     */
    publishPath?: pulumi.Input<string | undefined>;
    /**
     * Enable [pull request previews](https://render.com/docs/pull-request-previews#pull-request-previews-git-backed) for the service.
     *
     * @deprecated Deprecated
     */
    pullRequestPreviewsEnabled?: pulumi.Input<boolean | undefined>;
    /**
     * URL of the git repository to build.
     */
    repoUrl: pulumi.Input<string>;
    /**
     * When you specify a [root directory](https://render.com/docs/monorepo-support#root-directory), Render runs all your commands in the specified directory and ignores changes outside the directory. Defaults to the repository root.
     */
    rootDirectory?: pulumi.Input<string | undefined>;
    /**
     * List of [redirect and rewrite rules](https://render.com/docs/redirects-rewrites) to apply to a static site.
     */
    routes?: pulumi.Input<pulumi.Input<inputs.StaticSiteRoute>[] | undefined>;
}
