// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class Webhook extends pulumi.CustomResource {
    /**
     * Get an existing Webhook resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: WebhookState, opts?: pulumi.CustomResourceOptions): Webhook {
        return new Webhook(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'render:index/webhook:Webhook';

    /**
     * Returns true if the given object is an instance of Webhook.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Webhook {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Webhook.__pulumiType;
    }

    /**
     * whether or not the webhook is enabled
     */
    declare public readonly enabled: pulumi.Output<boolean>;
    /**
     * Filter webhooks to only these events. If empty, all webhooks will be sent.
     */
    declare public readonly eventFilters: pulumi.Output<string[] | undefined>;
    /**
     * Name of the webhook
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * The secret to verify webhook signatures.
     */
    declare public /*out*/ readonly secret: pulumi.Output<string>;
    /**
     * the URL to send webhooks to
     */
    declare public readonly url: pulumi.Output<string>;

    /**
     * Create a Webhook resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: WebhookArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: WebhookArgs | WebhookState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as WebhookState | undefined;
            resourceInputs["enabled"] = state?.enabled;
            resourceInputs["eventFilters"] = state?.eventFilters;
            resourceInputs["name"] = state?.name;
            resourceInputs["secret"] = state?.secret;
            resourceInputs["url"] = state?.url;
        } else {
            const args = argsOrState as WebhookArgs | undefined;
            if (args?.enabled === undefined && !opts.urn) {
                throw new Error("Missing required property 'enabled'");
            }
            if (args?.url === undefined && !opts.urn) {
                throw new Error("Missing required property 'url'");
            }
            resourceInputs["enabled"] = args?.enabled;
            resourceInputs["eventFilters"] = args?.eventFilters;
            resourceInputs["name"] = args?.name;
            resourceInputs["url"] = args?.url;
            resourceInputs["secret"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["secret"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(Webhook.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering Webhook resources.
 */
export interface WebhookState {
    /**
     * whether or not the webhook is enabled
     */
    enabled?: pulumi.Input<boolean | undefined>;
    /**
     * Filter webhooks to only these events. If empty, all webhooks will be sent.
     */
    eventFilters?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Name of the webhook
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * The secret to verify webhook signatures.
     */
    secret?: pulumi.Input<string | undefined>;
    /**
     * the URL to send webhooks to
     */
    url?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a Webhook resource.
 */
export interface WebhookArgs {
    /**
     * whether or not the webhook is enabled
     */
    enabled: pulumi.Input<boolean>;
    /**
     * Filter webhooks to only these events. If empty, all webhooks will be sent.
     */
    eventFilters?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Name of the webhook
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * the URL to send webhooks to
     */
    url: pulumi.Input<string>;
}
