"use client";

import {
  useState,
  useRef,
  useEffect,
  useLayoutEffect,
  useCallback,
} from "react";
import Link from "next/link";
import {
  X,
  Send,
  Loader2,
  Paperclip,
  ArrowDown,
  Plus,
  Coins,
  ChevronRight,
  Trash2,
  Maximize2,
  Minimize2,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Skeleton } from "@/components/ui/skeleton";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { useQueryClient } from "@tanstack/react-query";
import {
  AssistantBubble,
  UserBubble,
  type MessagePart,
  type SubagentPart,
} from "@/components/AgentMessage";
import {
  streamAgent,
  streamResume,
  uploadAgentFile,
  type ApprovalAction,
} from "@/lib/stream-agent";
import { getStoredToken, useScroogePanel, PANEL_MIN_WIDTH } from "@/lib/store";
import { apiFetch } from "@/lib/api-fetch";
import { useAgentSessions, useDeleteSession } from "@/hooks/useAgentSessions";
import { cn } from "@/lib/utils";

// ── Types ─────────────────────────────────────────────────────────────────────

type ChatMessage =
  | { id: string; role: "user"; content: string; attachments?: string[] }
  | { id: string; role: "assistant"; parts: MessagePart[]; streaming: boolean };

const SUGGESTIONS = [
  "What is my tax payable for YA 2025/26?",
  "How is my money bin growing?",
  "Where am I wasting money?",
  "Am I on track for FIRE?",
];

function truncate(s: string | null | undefined, n = 32): string {
  if (!s) return "Untitled session";
  return s.length > n ? s.slice(0, n) + "…" : s;
}

// ── Session dropdown ──────────────────────────────────────────────────────────

function SessionDropdown({
  currentThreadId,
  onSelect,
  onNew,
}: {
  currentThreadId: string;
  onSelect: (id: string) => void;
  onNew: () => void;
}) {
  const { data: sessions = [] } = useAgentSessions();
  const { mutate: deleteSession } = useDeleteSession();

  const current = sessions.find((s) => s.thread_id === currentThreadId);
  const label = current?.title ? truncate(current.title, 22) : "New chat";

  return (
    <DropdownMenu>
      <DropdownMenuTrigger
        render={
          <button className="flex items-center gap-1 text-[11px] text-[#F0EEE8]/50 hover:text-[#F0EEE8] transition-colors max-w-[160px]" />
        }
      >
        <span className="truncate">{label}</span>
        <ChevronRight className="size-3 shrink-0 rotate-90 opacity-60" />
      </DropdownMenuTrigger>
      <DropdownMenuContent align="start" className="w-60">
        <DropdownMenuItem
          onClick={onNew}
          className="gap-2 text-[12px]"
        >
          <Plus className="size-3.5" /> New chat
        </DropdownMenuItem>
        {sessions.length > 0 && <DropdownMenuSeparator />}
        {sessions.slice(0, 8).map((s) => (
          <DropdownMenuItem
            key={s.thread_id}
            className={cn(
              "flex items-center justify-between gap-2 text-[12px]",
              s.thread_id === currentThreadId && "font-medium"
            )}
            onClick={() => onSelect(s.thread_id)}
          >
            <span className="truncate flex-1">
              {truncate(s.title, 26) || "Untitled"}
            </span>
            <button
              className="shrink-0 opacity-0 group-hover:opacity-100 hover:text-destructive transition-opacity"
              onClick={(e) => {
                e.stopPropagation();
                deleteSession(s.thread_id);
                if (s.thread_id === currentThreadId) onNew();
              }}
            >
              <Trash2 className="size-3" />
            </button>
          </DropdownMenuItem>
        ))}
      </DropdownMenuContent>
    </DropdownMenu>
  );
}

// ── Main panel ────────────────────────────────────────────────────────────────

export function ScroogePanel() {
  const {
    isOpen, close, threadId, setThread,
    width, isFullPage, setWidth, toggleFullPage,
  } = useScroogePanel();
  const queryClient = useQueryClient();

  // Tracks UUIDs generated by this panel's "new chat" — skip history fetch for these
  const freshRef = useRef<Set<string>>(new Set([threadId]));
  const liveThreadRef = useRef<string | null>(null);

  const [messages, setMessages] = useState<ChatMessage[]>([]);
  const [input, setInput] = useState("");
  const [streaming, setStreaming] = useState(false);
  const [historyLoading, setHistoryLoading] = useState(false);
  const [pendingFiles, setPendingFiles] = useState<File[]>([]);
  const [uploadingFiles, setUploadingFiles] = useState(false);
  const [quotaBlocked, setQuotaBlocked] = useState(false);

  const scrollRef = useRef<HTMLDivElement>(null);
  const abortRef = useRef<AbortController | null>(null);
  const fileInputRef = useRef<HTMLInputElement>(null);
  const awaitingApprovalRef = useRef<{ msgId: string; partIndex: number } | null>(null);
  const messagesRef = useRef<ChatMessage[]>([]);
  const resumingRef = useRef(false);
  const atBottomRef = useRef(true);
  const [showScrollBtn, setShowScrollBtn] = useState(false);

  useEffect(() => { messagesRef.current = messages; }, [messages]);

  // Load history when threadId changes or panel opens
  useEffect(() => {
    if (!isOpen) return;
    if (threadId === liveThreadRef.current) return;

    liveThreadRef.current = null;
    setStreaming(false);
    if (awaitingApprovalRef.current) {
      abortRef.current?.abort();
      awaitingApprovalRef.current = null;
    }

    // Fresh thread — no history to load
    if (freshRef.current.has(threadId)) {
      setMessages([]);
      setHistoryLoading(false);
      return;
    }

    const token = getStoredToken();
    if (!token) { setHistoryLoading(false); return; }

    let cancelled = false;
    setMessages([]);
    setHistoryLoading(true);

    type HistoryMsg =
      | { role: "user"; content: string }
      | { role: "assistant"; parts: MessagePart[] };

    apiFetch<{ messages: HistoryMsg[] }>("GET", `/agent/history/${threadId}`)
      .then(({ messages: history }) => {
        if (cancelled) return;
        setMessages(
          (history ?? []).map((m) =>
            m.role === "user"
              ? { id: crypto.randomUUID(), role: "user" as const, content: m.content }
              : { id: crypto.randomUUID(), role: "assistant" as const, parts: m.parts ?? [], streaming: false }
          )
        );
      })
      .catch(console.error)
      .finally(() => { if (!cancelled) setHistoryLoading(false); });

    return () => { cancelled = true; };
  }, [threadId, isOpen]);

  // ── Scroll ────────────────────────────────────────────────────────────────

  function scrollToBottom(smooth = false) {
    const el = scrollRef.current;
    if (!el) return;
    if (smooth) el.scrollTo({ top: el.scrollHeight, behavior: "smooth" });
    else el.scrollTop = el.scrollHeight;
    atBottomRef.current = true;
    setShowScrollBtn(false);
  }

  function handleScroll() {
    const el = scrollRef.current;
    if (!el) return;
    const dist = el.scrollHeight - el.scrollTop - el.clientHeight;
    const near = dist < 80;
    atBottomRef.current = near;
    setShowScrollBtn(!near);
  }

  useLayoutEffect(() => {
    if (atBottomRef.current) scrollToBottom(false);
  }, [messages]);

  // ── Stream processing ─────────────────────────────────────────────────────

  function updateAssistantParts(msgId: string, updater: (p: MessagePart[]) => MessagePart[]) {
    setMessages((prev) =>
      prev.map((m) =>
        m.id === msgId && m.role === "assistant"
          ? { ...m, parts: updater([...m.parts]) }
          : m
      )
    );
  }

  async function processEventStream(
    eventIter: AsyncGenerator<import("@/lib/stream-agent").AgentEvent>,
    msgId: string,
    parts: MessagePart[],
    signal: AbortSignal
  ) {
    function getOrCreateTextPart(): Extract<MessagePart, { type: "text" }> {
      const last = parts[parts.length - 1];
      if (last && last.type === "text") return last;
      const p: Extract<MessagePart, { type: "text" }> = { type: "text", content: "" };
      parts.push(p);
      return p;
    }

    function getOrCreateSubagentSection(agent: string): Extract<MessagePart, { type: "subagent_section" }> {
      const last = parts[parts.length - 1];
      if (last && last.type === "subagent_section" && last.agent === agent && last.active) return last;
      const s: Extract<MessagePart, { type: "subagent_section" }> = { type: "subagent_section", agent, parts: [], active: true };
      parts.push(s);
      return s;
    }

    function flushSubagentSection() {
      const last = parts[parts.length - 1];
      if (last && last.type === "subagent_section") last.active = false;
    }

    function sync() {
      setMessages((prev) =>
        prev.map((m) =>
          m.id === msgId && m.role === "assistant" ? { ...m, parts: [...parts] } : m
        )
      );
    }

    for await (const event of eventIter) {
      if (signal.aborted) break;

      if (event.type === "token") {
        flushSubagentSection();
        getOrCreateTextPart().content += event.content;
        sync();
      } else if (event.type === "subagent_start") {
        getOrCreateSubagentSection(event.agent);
        sync();
      } else if (event.type === "subagent_end") {
        flushSubagentSection();
        sync();
      } else if (event.type === "subagent_token") {
        const section = getOrCreateSubagentSection(event.agent);
        const last = section.parts[section.parts.length - 1];
        if (last && last.type === "token") last.content += event.content;
        else section.parts.push({ type: "token", content: event.content });
        sync();
      } else if (event.type === "tool_call") {
        if (event.agent) {
          const section = getOrCreateSubagentSection(event.agent);
          const sub: SubagentPart = { type: "tool_call", name: event.name, input: event.input, done: false };
          section.parts.push(sub);
        } else {
          parts.push({ type: "tool_call", name: event.name, input: event.input, done: false });
        }
        sync();
      } else if (event.type === "tool_result") {
        if (event.agent) {
          const section = [...parts].reverse().find(
            (p) => p.type === "subagent_section" && p.agent === event.agent
          ) as Extract<MessagePart, { type: "subagent_section" }> | undefined;
          if (section) {
            for (let i = section.parts.length - 1; i >= 0; i--) {
              const p = section.parts[i];
              if (p.type === "tool_call" && p.name === event.name && !p.done) {
                p.done = true; p.output = String(event.output ?? ""); break;
              }
            }
          }
        } else {
          for (let i = parts.length - 1; i >= 0; i--) {
            const p = parts[i];
            if (p.type === "tool_call" && p.name === event.name && !p.done) {
              p.done = true; p.output = String(event.output ?? ""); break;
            }
          }
        }
        sync();
      } else if (event.type === "approval_required") {
        const ap: Extract<MessagePart, { type: "approval" }> = {
          type: "approval",
          action: event.action as ApprovalAction,
          status: "pending",
        };
        parts.push(ap);
        awaitingApprovalRef.current = { msgId, partIndex: parts.length - 1 };
        sync();
        return "awaiting_approval";
      } else if (event.type === "quota_exceeded") {
        setQuotaBlocked(true);
        sync();
        return "quota";
      } else if (event.type === "error") {
        getOrCreateTextPart().content += `\n\n_Error: ${event.message}_`;
        sync();
        break;
      } else if (event.type === "done") {
        break;
      }
    }
    return "done";
  }

  // ── Send ──────────────────────────────────────────────────────────────────

  const send = useCallback(async () => {
    const text = input.trim();
    if (!text || streaming) return;
    const token = getStoredToken();
    if (!token) return;

    let fileRefs: string[] = [];
    const fileNames = pendingFiles.map((f) => f.name);
    if (pendingFiles.length > 0) {
      setUploadingFiles(true);
      try {
        const results = await Promise.all(pendingFiles.map((f) => uploadAgentFile(token, f)));
        fileRefs = results.map((r) => r.file_ref);
      } catch { /* continue without files */ }
      finally { setUploadingFiles(false); setPendingFiles([]); }
    }

    const userMsg: ChatMessage = {
      id: crypto.randomUUID(), role: "user", content: text,
      attachments: fileNames.length ? fileNames : undefined,
    };
    const assistantId = crypto.randomUUID();
    const assistantMsg: ChatMessage = { id: assistantId, role: "assistant", parts: [], streaming: true };

    setMessages((prev) => [...prev, userMsg, assistantMsg]);
    setInput("");
    setStreaming(true);
    liveThreadRef.current = threadId;

    const controller = new AbortController();
    abortRef.current = controller;
    const parts: MessagePart[] = [];

    try {
      const result = await processEventStream(
        streamAgent(token, text, threadId, controller.signal, fileRefs.length ? fileRefs : undefined),
        assistantId, parts, controller.signal,
      );
      if (result === "awaiting_approval") return;
      if (result === "quota") {
        setMessages((prev) => prev.filter((m) => m.id !== assistantId && m.id !== userMsg.id));
        setInput(text);
      }
    } catch (err) {
      if ((err as Error).name !== "AbortError") {
        const tp = parts.find((p) => p.type === "text") as Extract<MessagePart, { type: "text" }> | undefined;
        if (tp) tp.content = tp.content || "Sorry, something went wrong. Please try again.";
        else parts.push({ type: "text", content: "Sorry, something went wrong. Please try again." });
        setMessages((prev) =>
          prev.map((m) => m.id === assistantId && m.role === "assistant" ? { ...m, parts: [...parts] } : m)
        );
      }
    } finally {
      if (!awaitingApprovalRef.current) {
        setMessages((prev) =>
          prev.map((m) => m.id === assistantId && m.role === "assistant" ? { ...m, streaming: false } : m)
        );
        setStreaming(false);
        setTimeout(() => queryClient.invalidateQueries({ queryKey: ["agent-sessions"] }), 1800);
      }
    }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [input, streaming, threadId, pendingFiles, queryClient]);

  const resumeDecision = useCallback(
    async (msgId: string, partIndex: number, decision: "approved" | "denied") => {
      const token = getStoredToken();
      if (!token || resumingRef.current) return;
      resumingRef.current = true;
      awaitingApprovalRef.current = null;

      const msg = messagesRef.current.find((m) => m.id === msgId && m.role === "assistant");
      const parts: MessagePart[] = msg && msg.role === "assistant" ? [...msg.parts] : [];
      const ap = parts[partIndex];
      if (ap && ap.type === "approval") parts[partIndex] = { ...ap, status: decision };
      updateAssistantParts(msgId, (p) => {
        const part = p[partIndex];
        if (part && part.type === "approval") part.status = decision;
        return p;
      });

      const controller = new AbortController();
      abortRef.current = controller;
      setStreaming(true);
      try {
        await processEventStream(
          streamResume(token, threadId, decision, controller.signal),
          msgId, parts, controller.signal,
        );
      } finally {
        resumingRef.current = false;
        setMessages((p) =>
          p.map((m) => m.id === msgId && m.role === "assistant" ? { ...m, streaming: false } : m)
        );
        setStreaming(false);
      }
    },
    [threadId]
  );

  const handleApprove = useCallback((msgId: string, i: number) => resumeDecision(msgId, i, "approved"), [resumeDecision]);
  const handleDeny = useCallback((msgId: string, i: number) => resumeDecision(msgId, i, "denied"), [resumeDecision]);

  // ── Thread management ─────────────────────────────────────────────────────

  function handleNewThread() {
    if (abortRef.current) abortRef.current.abort();
    const id = crypto.randomUUID();
    freshRef.current.add(id);
    setThread(id);
    setMessages([]);
    setStreaming(false);
    setPendingFiles([]);
    setQuotaBlocked(false);
  }

  function handleSelectThread(id: string) {
    if (abortRef.current) abortRef.current.abort();
    setThread(id);
    setStreaming(false);
    setPendingFiles([]);
    setQuotaBlocked(false);
  }

  function handleKeyDown(e: React.KeyboardEvent<HTMLTextAreaElement>) {
    if (e.key === "Enter" && !e.shiftKey) { e.preventDefault(); send(); }
  }

  // ── Resize ────────────────────────────────────────────────────────────────

  function handleResizeMouseDown(e: React.MouseEvent) {
    e.preventDefault();
    const onMouseMove = (ev: MouseEvent) => {
      const newWidth = Math.max(PANEL_MIN_WIDTH, Math.min(window.innerWidth - 60, window.innerWidth - ev.clientX));
      setWidth(newWidth);
    };
    const onMouseUp = () => {
      window.removeEventListener("mousemove", onMouseMove);
      window.removeEventListener("mouseup", onMouseUp);
    };
    window.addEventListener("mousemove", onMouseMove);
    window.addEventListener("mouseup", onMouseUp);
  }

  // ── Render ────────────────────────────────────────────────────────────────

  return (
    <div
      suppressHydrationWarning
      className={cn(
        "fixed z-50 flex flex-col overflow-hidden bg-[#010001]",
        "transition-transform duration-200 ease-in-out",
        isOpen ? "translate-x-0" : "translate-x-[calc(100%+1rem)]",
        isFullPage
          ? "inset-0 rounded-none"
          : "top-4 right-4 bottom-4 rounded-[28px]"
      )}
      style={
        !isFullPage
          ? {
              width: `${width}px`,
              boxShadow: "0 24px 64px rgba(0,0,0,0.40), 0 4px 16px rgba(0,0,0,0.24)",
            }
          : undefined
      }
    >
      {/* Drag-to-resize handle */}
      {!isFullPage && (
        <div
          aria-hidden
          className="absolute -left-1 top-0 h-full w-3 cursor-col-resize z-10 group"
          onMouseDown={handleResizeMouseDown}
        >
          <div className="absolute left-1 top-0 h-full w-px bg-white/8 group-hover:bg-white/20 transition-colors" />
        </div>
      )}

      {/* Header */}
      <div className={cn(
        "flex items-center justify-between px-5 py-4 shrink-0",
        !isFullPage && "rounded-t-[28px]",
      )}>
        <div className="flex items-center gap-3 min-w-0">
          <div className="size-8 rounded-[12px] bg-[#E8FC85] flex items-center justify-center shrink-0">
            <img src="/scrooge-duck.png" alt="Scrooge" className="size-5 object-contain" />
          </div>
          <div className="flex flex-col min-w-0">
            <span className="text-[13px] font-extrabold text-white tracking-[-0.02em] leading-none mb-0.5">Scrooge</span>
            <SessionDropdown
              currentThreadId={threadId}
              onSelect={handleSelectThread}
              onNew={handleNewThread}
            />
          </div>
        </div>
        <div className="flex items-center gap-0.5 shrink-0">
          <button
            onClick={handleNewThread}
            className="p-2 rounded-[10px] text-white/40 hover:text-white hover:bg-white/10 transition-colors"
            title="New chat"
          >
            <Plus className="size-3.5" />
          </button>
          <button
            onClick={toggleFullPage}
            className="p-2 rounded-[10px] text-white/40 hover:text-white hover:bg-white/10 transition-colors"
            title={isFullPage ? "Exit full page" : "Full page mode"}
          >
            {isFullPage ? <Minimize2 className="size-3.5" /> : <Maximize2 className="size-3.5" />}
          </button>
          <button
            onClick={close}
            className="p-2 rounded-[10px] text-white/40 hover:text-white hover:bg-white/10 transition-colors"
            title="Close"
          >
            <X className="size-3.5" />
          </button>
        </div>
      </div>

      {/* Divider */}
      <div className="h-px bg-white/8 mx-5" />

      {/* Message list — force dark tokens so bubble colors work on #010001 bg */}
      <div className="dark relative flex-1 min-h-0">
        <div
          ref={scrollRef}
          onScroll={handleScroll}
          className="h-full overflow-y-auto"
          style={{ scrollbarWidth: "none" }}
        >
          <div className={cn("px-4 py-5 space-y-5 pb-3", isFullPage && "max-w-3xl mx-auto px-8")}>
            {historyLoading && (
              <div className="space-y-3">
                {[...Array(3)].map((_, i) => (
                  <Skeleton key={i} className={`h-9 bg-white/8 ${i % 2 === 0 ? "w-3/4" : "w-1/2 ml-auto"}`} />
                ))}
              </div>
            )}

            {!historyLoading && messages.length === 0 && (
              <div className="flex flex-col items-center text-center gap-6 pt-10 px-1">
                <img
                  src="/scrooge-duck.png"
                  alt="Scrooge"
                  className="size-24 object-contain"
                  style={{ filter: "brightness(0) invert(1)" }}
                />
                <div className="space-y-2">
                  <h2 className="text-[17px] font-extrabold text-white tracking-[-0.04em]">Scrooge McDuck</h2>
                  <p className="text-[12.5px] text-white/55 leading-relaxed max-w-[210px]">
                    Hah! You&apos;ve come to the right place. I know every rupee in your money bin.
                  </p>
                </div>
                <div className="flex flex-col gap-2 w-full">
                  {SUGGESTIONS.map((q) => (
                    <button
                      key={q}
                      onClick={() => setInput(q)}
                      className="group flex items-center justify-between gap-3 text-left bg-white/5 hover:bg-white/10 border border-white/8 hover:border-[#E8FC85]/30 rounded-[14px] px-4 py-3 transition-all"
                    >
                      <span className="text-[12px] font-medium text-white/60 group-hover:text-white/90 transition-colors leading-snug">{q}</span>
                      <ChevronRight className="size-3.5 text-white/20 group-hover:text-[#E8FC85] shrink-0 transition-colors" />
                    </button>
                  ))}
                </div>
              </div>
            )}

            {messages.map((m) => (
              <div key={m.id} style={{ animation: "msg-in 0.18s ease-out both" }}>
                {m.role === "user" ? (
                  <UserBubble content={m.content} attachments={m.attachments} />
                ) : (
                  <AssistantBubble
                    parts={m.parts}
                    streaming={m.streaming}
                    onApprove={(i) => handleApprove(m.id, i)}
                    onDeny={(i) => handleDeny(m.id, i)}
                  />
                )}
              </div>
            ))}
          </div>
        </div>

        {showScrollBtn && (
          <div className="absolute bottom-3 left-1/2 -translate-x-1/2 z-10" style={{ animation: "msg-in 0.15s ease-out both" }}>
            <button
              onClick={() => scrollToBottom(true)}
              className="flex items-center gap-1.5 px-3.5 py-1.5 rounded-full bg-[#E8FC85] text-[#010001] text-[11px] font-bold shadow-lg hover:brightness-95 active:scale-95 transition-all"
            >
              <ArrowDown className="size-3" /> Bottom
            </button>
          </div>
        )}
      </div>

      {/* Composer */}
      <div className={cn("px-4 pb-4 pt-3 shrink-0", isFullPage && "max-w-3xl mx-auto w-full px-8")}>
        {quotaBlocked && (
          <div className="flex items-center justify-between gap-2 mb-3 rounded-[14px] bg-white/6 border border-white/10 px-4 py-2.5">
            <p className="text-[11px] text-white/55">Monthly messages used up. Upgrade to continue.</p>
            <Link href="/settings" className="shrink-0 text-[11px] font-bold bg-[#E8FC85] text-[#010001] rounded-full px-3 py-1 hover:brightness-95 transition-all">
              Upgrade
            </Link>
          </div>
        )}

        {pendingFiles.length > 0 && (
          <div className="flex flex-wrap gap-1.5 mb-2.5">
            {pendingFiles.map((f, i) => (
              <span key={i} className="inline-flex items-center gap-1 text-[10px] bg-white/8 border border-white/12 rounded-full px-2.5 py-1 text-white/60">
                {f.name}
                <button onClick={() => setPendingFiles((p) => p.filter((_, j) => j !== i))} className="hover:text-white transition-colors">
                  <X className="size-2.5" />
                </button>
              </span>
            ))}
          </div>
        )}

        <div className="bg-white/6 border border-white/10 rounded-[20px] focus-within:border-white/20 transition-colors overflow-hidden">
          <input
            ref={fileInputRef}
            type="file"
            className="hidden"
            accept=".pdf,.txt,.csv,.png,.jpg,.jpeg,.xlsx"
            multiple
            onChange={(e) => {
              const files = Array.from(e.target.files ?? []);
              if (files.length) setPendingFiles((p) => [...p, ...files]);
              e.target.value = "";
            }}
          />

          <Textarea
            value={input}
            onChange={(e) => setInput(e.target.value)}
            onKeyDown={handleKeyDown}
            placeholder="Ask Scrooge…"
            className="resize-none min-h-[42px] max-h-36 text-[13px] pt-3.5 pb-1 px-4 border-0 shadow-none focus-visible:ring-0 bg-transparent flex-1 w-full text-white placeholder:text-white/30 leading-relaxed"
            rows={1}
            disabled={streaming}
          />

          {/* Toolbar row */}
          <div className="flex items-center justify-between px-3 pb-2.5 pt-1">
            <button
              type="button"
              onClick={() => fileInputRef.current?.click()}
              disabled={streaming || uploadingFiles}
              className="p-1.5 rounded-lg text-white/30 hover:text-white/60 hover:bg-white/8 disabled:opacity-40 transition-colors"
            >
              {uploadingFiles ? <Loader2 className="size-4 animate-spin" /> : <Paperclip className="size-4" />}
            </button>

            <button
              onClick={send}
              disabled={streaming || !input.trim()}
              className="h-8 w-8 rounded-[11px] shrink-0 flex items-center justify-center bg-[#E8FC85] text-[#010001] hover:brightness-95 disabled:opacity-25 transition-all active:scale-[0.96]"
            >
              {streaming ? <Loader2 className="size-3.5 animate-spin" /> : <Send className="size-3.5" />}
            </button>
          </div>
        </div>

        <p className="text-[9px] text-white/18 text-center mt-2">
          Numbers from deterministic engine · Write actions need your approval
        </p>
      </div>
    </div>
  );
}

// ── Toggle button (for header) ────────────────────────────────────────────────

export function ScroogeToggle() {
  const { toggle, isOpen } = useScroogePanel();
  return (
    <button
      onClick={toggle}
      className={cn(
        "flex items-center gap-1.5 px-2.5 py-1 rounded-lg text-[12px] font-medium transition-colors",
        isOpen
          ? "bg-sidebar text-sidebar-foreground"
          : "text-muted-foreground hover:text-foreground hover:bg-accent"
      )}
      title="Ask Scrooge"
    >
      <Coins className="size-3.5 shrink-0" />
      <span className="hidden sm:inline">Scrooge</span>
    </button>
  );
}
